version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
      - yarn global add serverless
  build:
    commands:
      - echo $PROD_MONGODB_URI
      - sls deploy
cache:
  paths:
    - '/node_modules/**/*'
