version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install --frozen-lockfile
      - yarn global add serverless
      - yarn global add knex
  build:
    commands:
      - knex migrate:latest --esm
      - sls deploy
# cache:
#   paths:
#     - '/node_modules/**/*'
