service: nickmonaco-rss-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-plugin-warmup

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  currentStage: ${opt:stage, "dev"}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    # warmup:
    #   enabled: true
    #   prewarm: true
    #   name: ${self:service}-lambda-warmer
    #   concurrency: 1

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 60 # optional, in seconds, default is 6
  versionFunctions: false
  stage: ${self:custom.currentStage}
  environment:
    SECRET: ${env:SECRET, file(./.env.yml):SECRET}
    PROXYENDPOINT: ${env:PROXYENDPOINT, file(./.env.yml):PROXYENDPOINT}
    STAGE: ${self:custom.currentStage}
    DBNAME: ${env:DBNAME, file(./.env.yml):DBNAME}
    DBPASSWORD: ${env:DBPASSWORD, file(./.env.yml):DBPASSWORD}
    DBUSER: ${env:DBUSER, file(./.env.yml):DBUSER}
    # ORIGIN_DOMAIN: ${env:ORIGIN_DOMAIN, file(./.env.yml):ORIGIN_DOMAIN}
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
