org: nickmonaco
app: nickmonaco-rss-api
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs10.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
